import { expect } from 'chai';
import { generateMarkdownReport } from '../../src/utils/reportGenerator.js';

describe('generateMarkdownReport', () => {
  it('should generate valid markdown with table header and rows', () => {
    const report = generateMarkdownReport({
      orgAlias: 'testOrg',
      fileName: 'fullManifest.xml',
      types: [
        { name: 'ApexClass', memberCount: 10, members: [], firstMember: '', lastMember: '' },
        { name: 'CustomObject', memberCount: 5, members: [], firstMember: '', lastMember: '' },
      ],
      totalTypes: 2,
      totalMembers: 15,
    });

    expect(report).to.include('# Manifest Analysis Report');
    expect(report).to.include('**Org**: testOrg');
    expect(report).to.include('**File**: fullManifest.xml');
    expect(report).to.include('| 1 | ApexClass | 10 |');
    expect(report).to.include('| 2 | CustomObject | 5 |');
    expect(report).to.include('**Total: 2 types**');
    expect(report).to.include('**15**');
  });

  it('should include generation timestamp', () => {
    const report = generateMarkdownReport({
      orgAlias: 'org',
      fileName: 'test.xml',
      types: [],
      totalTypes: 0,
      totalMembers: 0,
    });

    expect(report).to.include('**Generated**:');
  });

  it('should include footer', () => {
    const report = generateMarkdownReport({
      orgAlias: 'org',
      fileName: 'test.xml',
      types: [],
      totalTypes: 0,
      totalMembers: 0,
    });

    expect(report).to.include('*Generated by sf dgjw manifest generate*');
  });
});
